### PR TITLE
T6508: pr workflows updated for branch and target

### PR DESCRIPTION
**Pull request by kumvijaya**
T6508: pr workflows updated for branch and target
## Change Summary

T6508: pr workflows updated for branch and target
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6508

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by kumvijaya** [comment]
@MergifyIo backport equuleus

**Comment by kumvijaya** [comment]
@MergifyIo backport circinus

**Comment by kumvijaya** [comment]
@MergifyIo backport sagitta

**Comment by c-po** [comment]
@kumvijaya backporting makes no sense in this case, as Sagitta needs to use the sagitta branch of the workflow, same applies to circinus.

**Comment by kumvijaya** [comment]
Ok, sure

**Comment by kumvijaya** [comment]
@c-po  Removed backports

**Review by c-po — APPROVED** [review]

**Review by sever-sever — APPROVED** [review]

**Pull request merged**
