### PR TITLE
Lanner: Add build procedure for Lanner NCA-25XX devices

### PR DESCRIPTION
**Pull request by DmitriyEshenko**
## Types of changes

 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I wonder why this can not be part of the base image. With udev it is possible to probe if certaun ids are present on the system (like model) and only if so the rule is execuded. Usung this approach all cutom ISOs can be shrinked to the generic one.

**Comment by DmitriyEshenko** [comment]
Unfortunately, Lanner devices do not have filled DMI info, so we need to build ISO per model

**Comment by c-po** [comment]
But I guess Lanner devices use a Lanner MAC address? You can then do the combination of the systems base mac address and the PCIe port?

**Comment by DmitriyEshenko** [comment]
Yes, we can but it does not resolve the issue with detecting  models that might have different BUS ID

**Pull request merged**
