### PR TITLE
T201 -  Beep When Fully Booted

### PR DESCRIPTION
**Pull request by hagbard-01**
I'm offline for a week, due to some travelling. Will do the interface definition once I'm back. The basic idea is to play a sound via pc speaker (kernel module is loaded) once the login target has been reached. The interface will then one do a systemctl <enable|disable> beep. Have a look and let me if I need to change anything.

### CODE REVIEW

**Comment by c-po** [comment]
Thanks for the contribution. To me this looks like it is always executed on system startup and not configurable as mentioned in https://phabricator.vyos.net/T201. Am I right?

**Comment by hagbard-01** [comment]
Hi C-po,
nope you are wrong. Debian uses systemd as default init since jessie, what I did is just a unit which is deactivated per default, so nothing will beep per default. I've added the beep package to the build and the systemd unit script so far. I do the interface to activate/deactivate this week, so it fits exactly the requested item. Right now the interface to activate/deactivate is still missing. I was away for 8 days with no internet connection.

**Comment by hagbard-01** [comment]
is this going to be merged at one point?

**Comment by c-po** [comment]
I'm currently verifying the whole system beep stuff so please be patient.

**Comment by c-po** [comment]
Beep implementation now works without systemd. Thanks for the contribution.

**Pull request closed without merging**
