### PR TITLE
T5754 strongswan upgrade

### PR DESCRIPTION
**Pull request by GurliGebis**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5754

## Component(s) name

strongswan

## Proposed changes

Upgrade to 5.9.11

## How to test

1. Build new packages for strongswan
2. Build new ISO with these packages
3. Update to that image

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Initial tests show that build smoketests passed with the new version, thanks.

Why was this patch `packages/strongswan/patches/0005-vici-add-soft-lifetime-calculation-if-hard-lifetime-configured.patch` removed? Did it get upstreamed? If so, can you show us the commit?

**Comment by GurliGebis** [comment]
@c-po yes, it has been upstreamed.
I verified the changes are already in there, so it is safe to remove 🙂

**Comment by GurliGebis** [comment]
@c-po is there anything I need to do to get this merged?

**Comment by sever-sever** [comment]
Will it affect nhrp?

**Comment by c-po** [comment]
> Will it affect nhrp?

Yes, those modified patches are for DMVPN/NHRP.
So it needs testing

**Comment by GurliGebis** [comment]
@c-po okay, I don't know about those two, so I don't know how to test that.
Can you test it?

**Comment by c-po** [comment]
@GurliGebis 

please note that your changes will not automatically build in our docker environment, as the listed `systemd-dev` package dependency is not available in Debian 12. I needed to add the following code to make it build, please add this to your PR:

```diff
diff --git i/packages/strongswan/Jenkinsfile w/packages/strongswan/Jenkinsfile
index bd884ee92..d79941d70 100644
--- i/packages/strongswan/Jenkinsfile
+++ w/packages/strongswan/Jenkinsfile
@@ -23,7 +23,7 @@ def pkgList = [
     ['name': 'strongswan',
      'scmCommit': 'debian/5.9.11-2',
      'scmUrl': 'https://salsa.debian.org/debian/strongswan.git',
-     'buildCmd': 'sudo mk-build-deps --install --tool "apt-get --yes --no-install-recommends"; cd ..; ./build.sh'],
+     'buildCmd': 'cd ..; ./build.sh'],
 ]

 // Start package build using library function from https://github.com/vyos/vyos-build
diff --git i/packages/strongswan/build.sh w/packages/strongswan/build.sh
index e12d54f09..c0dab4d51 100755
--- i/packages/strongswan/build.sh
+++ w/packages/strongswan/build.sh
@@ -2,6 +2,35 @@
 CWD=$(pwd)
 set -e

+# extracted build dependencies, as autogenerationg and installing them will fail :/
+sudo apt-get install -y bison \
+    bzip2 \
+    debhelper-compat \
+    dh-apparmor \
+    dpkg-dev  \
+    flex \
+    gperf \
+    libiptc-dev \
+    libcap-dev \
+    libcurl3-dev \
+    libgcrypt20-dev \
+    libgmp3-dev \
+    libkrb5-dev \
+    libldap2-dev \
+    libnm-dev \
+    libpam0g-dev \
+    libsqlite3-dev \
+    libssl-dev \
+    libsystemd-dev \
+    libtool \
+    libtss2-dev \
+    libxml2-dev \
+    pkg-config \
+    po-debconf \
+    systemd \
+    libsystemd-dev \
+    tzdata
+
 SRC=strongswan
 if [ ! -d ${SRC} ]; then
     echo "Source directory does not exists, please 'git clone'"
@@ -24,4 +53,4 @@ echo "I: bump version"
 dch -v "5.9.11-2+vyos0" "Patchset for DMVPN support" -b

 echo "I: Build Debian Package"
-dpkg-buildpackage -uc -us -tc -b
+dpkg-buildpackage -uc -us -tc -b -d
```

For the DMVPN/NHRP test I'm currently working in my lab on it

**Comment by GurliGebis** [comment]
@c-po I have added the changes and pushed them :)

**Comment by c-po** [comment]
I can confirm basic NHRP reachability is working in this setup based on our documentation https://docs.vyos.io/en/equuleus/configuration/vpn/dmvpn.html#example

image

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Comment by GurliGebis** [comment]
@c-po can I trigger a backport PR, or do you need to do it?

**Comment by c-po** [comment]
We will backport it once we think it matured

**Comment by c-po** [comment]
@mergifyio backport sagitta

**Pull request merged**
