### PR TITLE
frr: T5123: Add patch to support show detailed ospf route table

### PR DESCRIPTION
**Pull request by rgwan**
## Change Summary

Allows user easily distinguish route items by router that originates it.

Suggest to backport to v1.3.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5123

## Component(s) name

ospfd

## How to test

Use vtysh command `show ip ospf route detail` to shown detailed information.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Is there any chance to get this backported into FRR [stable/8.5](https://github.com/frrouting/frr/tree/stable/8.5) branch?

**Comment by sever-sever** [comment]
> Is there any chance to get this backported into FRR [stable/8.5](https://github.com/frrouting/frr/tree/stable/8.5) branch?

There is PR for FRR https://github.com/FRRouting/frr/pull/13140

**Comment by rgwan** [comment]
> > Is there any chance to get this backported into FRR [stable/8.5](https://github.com/frrouting/frr/tree/stable/8.5) branch?
> 
> There is PR for FRR [FRRouting/frr#13140](https://github.com/FRRouting/frr/pull/13140)

Two weeks passed... Maybe we should take these patches in first?

**Comment by rgwan** [comment]
@c-po  Can we merge it first, and delete it when upstream accepted this patch?

**Comment by dmbaturin** [comment]
I'd be inclined to merge it now and remove later.

Also, is this PR a _prerequisite_ for https://github.com/vyos/vyos-1x/pull/1921 ?

**Comment by c-po** [comment]
> I'd be inclined to merge it now and remove later.
> 
> Also, is this PR a _prerequisite_ for [vyos/vyos-1x#1921](https://github.com/vyos/vyos-1x/pull/1921) ?

Yes it is

**Comment by rgwan** [comment]
> > I'd be inclined to merge it now and remove later.
> > Also, is this PR a _prerequisite_ for [vyos/vyos-1x#1921](https://github.com/vyos/vyos-1x/pull/1921) ?
> 
> Yes it is

So strange, It seems the patch is not correctly applied. Do we have artifacts about that?

```
vyos@bluespc-asbr1:~$ show ip ospf route detail 
% OSPFv3 instance not found
vyos@bluespc-asbr1:~$ vtysh
bluespc-asbr1# show ip ospf r 
  <cr>  
  json  JavaScript Object Notation
  pce   PCE information
bluespc-asbr1# show ip ospf r pce
  PCE info is disabled on this router
bluespc-asbr1# show ver
FRRouting 8.5 (bluespc-asbr1) on Linux(6.1.25-amd64-vyos).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
    '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--localstatedir=/var/run/frr' '--sbindir=/usr/lib/frr' '--sysconfdir=/etc/frr' '--with-vtysh-pager=/usr/bin/pager' '--libdir=/usr/lib/x86_64-linux-gnu/frr' '--with-moduledir=/usr/lib/x86_64-linux-gnu/frr/modules' '--disable-dependency-tracking' '--enable-rpki' '--disable-scripting' '--enable-pim6d' '--with-libpam' '--enable-doc' '--enable-doc-html' '--enable-snmp' '--enable-fpm' '--disable-protobuf' '--disable-zeromq' '--enable-ospfapi' '--enable-bgp-vnc' '--enable-multipath=256' '--enable-user=frr' '--enable-group=frr' '--enable-vty-group=frrvty' '--enable-configfile-mask=0640' '--enable-logfile-mask=0640' 'build_alias=x86_64-linux-gnu' 'PYTHON=python3'
bluespc-asbr1# exit
vyos@bluespc-asbr1:~$ show ver
Version:          VyOS 1.4-rolling-202304261027
Release train:    current

Built by:         autobuild@vyos.net
Built on:         Wed 26 Apr 2023 10:27 UTC
Build UUID:       6dee870f-c04e-4282-a551-41db656e6a26
Build commit ID:  25cf22e2ebcf2f


```

**Comment by sever-sever** [comment]
```
13:45:18  + cd ..
13:45:18  + ./build-frr.sh
13:45:18  I: Apply FRRouting patches not in main repository:
13:45:18  error: patch failed: doc/user/ospfd.rst:824
13:45:18  error: doc/user/ospfd.rst: patch does not apply
13:45:18  hint: Use 'git am --show-current-patch=diff' to see the failed patch
13:45:18  Applying: ospfd: Support show advertise router in 'show ip ospf route' command
13:45:18  Patch failed at 0001 ospfd: Support show advertise router in 'show ip ospf route' command
13:45:18  When you have resolved this problem, run "git am --continue".
13:45:18  If you prefer to skip this patch, run "git am --skip" instead.
13:45:18  To restore the original branch and stop patching, run "git am --abort".
```

**Comment by rgwan** [comment]
> > > I'd be inclined to merge it now and remove later.
> > > Also, is this PR a _prerequisite_ for [vyos/vyos-1x#1921](https://github.com/vyos/vyos-1x/pull/1921) ?
> > 
> > 
> > Yes it is
> 
> So strange, It seems the patch is not correctly applied. Do we have artifacts about that?
> 
> ```
> vyos@bluespc-asbr1:~$ show ip ospf route detail 
> % OSPFv3 instance not found
> vyos@bluespc-asbr1:~$ vtysh
> bluespc-asbr1# show ip ospf r 
>   <cr>  
>   json  JavaScript Object Notation
>   pce   PCE information
> bluespc-asbr1# show ip ospf r pce
>   PCE info is disabled on this router
> bluespc-asbr1# show ver
> FRRouting 8.5 (bluespc-asbr1) on Linux(6.1.25-amd64-vyos).
> Copyright 1996-2005 Kunihiro Ishiguro, et al.
> configured with:
>     '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--localstatedir=/var/run/frr' '--sbindir=/usr/lib/frr' '--sysconfdir=/etc/frr' '--with-vtysh-pager=/usr/bin/pager' '--libdir=/usr/lib/x86_64-linux-gnu/frr' '--with-moduledir=/usr/lib/x86_64-linux-gnu/frr/modules' '--disable-dependency-tracking' '--enable-rpki' '--disable-scripting' '--enable-pim6d' '--with-libpam' '--enable-doc' '--enable-doc-html' '--enable-snmp' '--enable-fpm' '--disable-protobuf' '--disable-zeromq' '--enable-ospfapi' '--enable-bgp-vnc' '--enable-multipath=256' '--enable-user=frr' '--enable-group=frr' '--enable-vty-group=frrvty' '--enable-configfile-mask=0640' '--enable-logfile-mask=0640' 'build_alias=x86_64-linux-gnu' 'PYTHON=python3'
> bluespc-asbr1# exit
> vyos@bluespc-asbr1:~$ show ver
> Version:          VyOS 1.4-rolling-202304261027
> Release train:    current
> 
> Built by:         autobuild@vyos.net
> Built on:         Wed 26 Apr 2023 10:27 UTC
> Build UUID:       6dee870f-c04e-4282-a551-41db656e6a26
> Build commit ID:  25cf22e2ebcf2f
> ```

Ok I know why, I have to backport it from frr master branch to frr version 8.5. Git refused to apply patch to v8.5. I have submitted a new commit to do this, sorry about that.

https://github.com/rgwan/vyos-build/commit/4d73902eb9c6f048aabb5b90f2ddabbd375851a9

**Comment by rgwan** [comment]
@c-po This patch is merged by upstream, when our frr version bump to the version that has this patch, this commit can be reverted.

**Pull request merged**
