### PR TITLE
T6173: Fix build error when "--version" value contains "/"

### PR DESCRIPTION
**Pull request by rts-kotori**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Component(s) name

`vyos-build-image` script
## Proposed changes

Instead of not checking for any `/` in the `--version` string, it now replaces `/` to `_` so that the copy image step does not throw any error
## How to test

I have ran the build script after applying the changes to the build script, and confirmed that it fixes the issue stated above.
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Why do not use _ in the image version initially?

**Comment by rts-kotori** [comment]
> Why do not use _ in the image version initially?

I just discovered this bug accidentally and thought, why not fix it, since it is easy to fix.

**Comment by sever-sever** [comment]
I'd probably add `verify` to the image name.

**Comment by rts-kotori** [comment]
I don't seems to see any `verify` function in the build script or from any imports it is currently importing. What do you refer to by `verify`?

**Comment by c-po** [comment]
> I don't seems to see any `verify` function in the build script or from any imports it is currently importing. What do you refer to by `verify`?

A verification function should be added.

```python
for character in ['/', '~']:
    if character in version_data["version"]:
        exit(f'Version contains invalid character: {character}')
```

**Comment by dmbaturin** [comment]
Maybe just use a regex to disallow anything except `[0-9a-zA-Z\-\.\+]`?

**Comment by rts-kotori** [comment]
> > I don't seems to see any `verify` function in the build script or from any imports it is currently importing. What do you refer to by `verify`?
> 
> A verification function should be added.
> 
> ```python
> for character in ['/', '~']:
>     if character in version_data["version"]:
>         exit(f'Version contains invalid character: {character}')
> ```

What characters should be allowed by --version? In my tests, `~` didn't cause an error, only `/` did


> Maybe just use a regex to disallow anything except `[0-9a-zA-Z\-\.\+]`?

Why should other characters be blocked if it does not cause a build error?

**Comment by c-po** [comment]
> Why should other characters be blocked if it does not cause a build error?

Regular software engineering paranoia on operating systems. ~ marks the Linux home. Is there any reason to have a ~ in the version file or anything other then in `[0-9a-zA-Z\-\.\+]`? I guess we should keep it as simple as possible.

**Comment by jestabro** [comment]
Note that version_name is the default image_name during add/install, which has its own validation:
https://github.com/vyos/vyos-1x/blob/current/python/vyos/system/image.py#L236-L248
https://github.com/vyos/vyos-1x/blob/current/src/op_mode/image_installer.py#L863-L872

**Comment by c-po** [comment]
@rts-kotori thank you for pointing this out. This is now superseeded by https://github.com/vyos/vyos-build/pull/553

**Pull request closed without merging**
