### PR TITLE
T1132: Equuleus: package-build build against the new equuleus branches, package updates and kernel upgrade

### PR DESCRIPTION
**Pull request by runborg**
Updates for the build env. to be up2date with changes done the last few days.
* Updated all packages to build against the new equuleus branches
* kernel updated to kernel
* removed and updated changes in used packages.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Is equuleus in sync with current now?

**Comment by runborg** [comment]
No, they are not in sync, there is a lot of commits to both this current and a bunch of other currents that are not done on the equuleus branches. for now it is also not possible to automatically rebase vyos-build/equuleus against current i have not checked the other equuleus branches. i also have no way to automatically check for current->equuleus inconsistencies

**Comment by dmbaturin** [comment]
@runborg That's what bothers me about equuleus. We (let's not point fingers) let it diverge from current. Now we need to take responsibility for it, walk through both branches, and make sure no valuable commits are lost.

Else it's Vyatta's messed up master branch all over again.

**Comment by dmbaturin** [comment]
As in, last I checked, current couldn't be merged into equuleus without conflicts in vyos-1x for example. That's the time bomb we need to defuse _now_, before doing anything else.

**Comment by runborg** [comment]
@dmbaturin What is the issue in vyos-1x:current -> equuleus ? from my experience it merges just fine?   

vyos-build on the other hand does not merge fine, because of changes to the same sections to the same files

**Comment by runborg** [comment]
https://github.com/runborg/vyos-1x/tree/equuleus this branch is a rebase of vyos-1x current into the equuleus branch.

**Comment by c-po** [comment]
This branch has conflicts that must be resolved

**Comment by runborg** [comment]
half of this pr is already commited by @c-po and creating conflicts for this pr. also done another pr with full rebase

**Comment by c-po** [comment]
You also could have left this one open, resolve your conflicts and then force push.

**Pull request closed without merging**
