### PR TITLE
conntrack: T3275: disable conntrack modules by default for new installs

### PR DESCRIPTION
**Pull request by bstepler**
## Change Summary

Disable conntrack modules by default for new installs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [X] Other (please describe): default setting change for new installs

## Related Task(s)

* https://phabricator.vyos.net/T3275

## Component(s) name

conntrack

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by dmbaturin** [comment]
Those modules are already disabled by default in `current`, using a new default system config and a new VyOS CLI syntax where you have to enable them explicitly rather than disable them.

It's being backported to 1.3 now, so this change will break the backport (since there's no `disable` option anymore, it's the opposite—`enable`).

I appreciate your effort, sorry for not making that plan known to all contributors in time!

**Comment by bstepler** [comment]
@dmbaturin: this is not working as intended in 1.4-rolling-202109110217 (results from livecd, same as new install; note the `conntrack` entries):

```
vyos@vyos:~$ show configuration commands
set interfaces ethernet eth0 hw-id '52:54:00:09:0c:21'
set interfaces loopback lo
set system config-management commit-revisions '100'
set system conntrack modules ftp
set system conntrack modules h323
set system conntrack modules nfs
set system conntrack modules pptp
set system conntrack modules sip
set system conntrack modules sqlnet
set system conntrack modules tftp
set system console device ttyS0 speed '115200'
set system host-name 'vyos'
set system login user vyos authentication encrypted-password '$6$QxPS.uk6mfo$9QBSo8u1FkH16gMyAVhus6fU3LOzvLR9Z9.82m3tiHFAxTtIkhaZSWssSgzt4v4dGAL8rhVQxTg0oAG9/q11h/'
set system login user vyos authentication plaintext-password ''
set system ntp server time1.vyos.net
set system ntp server time2.vyos.net
set system ntp server time3.vyos.net
set system syslog global facility all level 'info'
set system syslog global facility protocols level 'debug'
vyos@vyos:~$ show version

Version:          VyOS 1.4-rolling-202109110217
Release Train:    sagitta

Built by:         autobuild@vyos.net
Built on:         Sat 11 Sep 2021 02:17 UTC
Build UUID:       b52ed9af-ec99-4874-8321-9eb09548927d
Build Commit ID:  1d3d0401eeb9e8

Architecture:     x86_64
Boot via:         livecd
System type:      KVM guest

Hardware vendor:  QEMU
Hardware model:   Standard PC (Q35 + ICH9, 2009)
Hardware S/N:     
Hardware UUID:    38e8ac83-9d6c-46e8-8cce-f738c772c27a

Copyright:        VyOS maintainers and contributors
```

This is because the `conntrack` migration script is running when the default config is loaded (indeed, all migration scripts run). This PR fixes the default config so the modules are properly disabled after migration.

**Comment by dmbaturin** [comment]
I wonder if the right solution is to start including current component versions in the default config.

**Comment by bstepler** [comment]
~If so, watch out for [`interfaces/20-to-21`](https://github.com/vyos/vyos-1x/blob/current/src/migration-scripts/interfaces/20-to-21) and anything similar.~

Never mind, that doesn't actually do anything when loading the default config (which is probably a bug, since the offload settings don't get set).

**Pull request closed without merging**
