### PR TITLE
T3664: Add support for local packages, generate apt release pinning

### PR DESCRIPTION
**Pull request by sarthurdev**
## Change Summary

Add support for local packages with new build system
Generate apt release pinning file instead of using APT::Default-Release (caused issue with local packages)

## Types of changes

 
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3664

## Component(s) name

build

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by jestabro** [comment]
@sarthurdev A naive test with a local package returns the error below; this may be a secondary issue, as the patch is clearly the right idea. I will take a closer look first thing tomorrow.

```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-jZ2Og6/381-vyos-1x_1.4dev0-3374-gdf23b1da_amd64.deb
N: Download is performed unsandboxed as root as file '/root/packages/./vyos-1x_1.4dev0-3374-gdf23b1da_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: An unexpected failure occurred, exiting...
```

**Comment by c-po** [comment]
I can second that.

```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-XqvWR7/392-vyos-1x_1.4dev0-3376-g3ddf5eb0+dirty_amd64.deb
N: Download is performed unsandboxed as root as file '/root/packages/./vyos-1x_1.4dev0-3376-g3ddf5eb0+dirty_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: An unexpected failure occurred, exiting...
```

**Comment by sarthurdev** [comment]
Very strange, I did get that error too but after wiping the build folder it's working on my end.

```
...
[2022-10-10 12:11:19] lb source 
P: Source stage disabled, skipping
P: \033[0;32mBuild completed successfully\033[0m
root@ad3577940d30:/vyos/vyos-build# git status
On branch sarthurdev_current
Your branch is up to date with 'sarthurdev/current'.
```

**Comment by jestabro** [comment]
@sarthurdev I did try it yesterday with a fresh checkout; no build dir, and still the error. I will check again, for sanity, and let you  know.

**Comment by jestabro** [comment]
Well, some sort of chicken-and-egg with permissions and the file:
`data/live-build-config/archives/vyos.pref.chroot`

If I run 'sudo make iso', rm the build directory, but leave the above file, and run again, it will succeed the second time.

**Comment by sarthurdev** [comment]
Adding the divert in PR https://github.com/vyos/vyos-1x/pull/1578 seems to fix this weirdness. 🤷‍♂️

**Pull request merged**
