### PR TITLE
T5604: List of debian archives is out of date (non-free-firmware is missing)

### PR DESCRIPTION
**Pull request by Apachez-**
## Change Summary

In Debian 12.x (bookworm) the "non-free" archive were splitted into "non-free" and "non-free-firmware".

This commit adds "non-free-firmware" as one of the archives to be used during build.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5604

## Component(s) name

build

## Proposed changes

Updated `debian_archive_areas` variable in `data/defaults.toml` so it becomes:

```
debian_archive_areas = "main contrib non-free non-free-firmware"
```

Due to this message during build:

```
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split
```

For more information regarding the split see:

https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split

## How to test

Verify that VyOS builds without errors and that smoketests completes.

Smoketest runned successfully without errors when this change was added:

```
DEBUG - echo EXITCODE:$?
 INFO - Smoketest finished successfully!
 INFO - Powering off system
DEBUG - EXITCODE:0poweroff now
 INFO - Shutting down virtual machine
 INFO - Waiting for shutdown...
DEBUG - poweroff now
 INFO - Waiting for shutdown...
DEBUG - poweroff now
 INFO - VM is shut down!
 INFO - Cleaning up
 INFO - Removing disk file: testinstall-20230920-100058-e915.img
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by sever-sever — APPROVED** [review]

**Comment by c-po** [comment]
Why do we need those firmware files?

We have our own `vyos-linux-firmware` package

**Comment by Apachez-** [comment]
Because the firmwares were part of the non-free archive previously but they are now their own archive today in Debian.

If the build doesnt fetch any firmware then the archive wont be used but it will be available (which it isnt prior to this commit).

This is handy specially for custom builds were you wont have to troubleshoot why a specific package who exists in Debian suddently doesnt install in the chroot build directory.

**Comment by c-po** [comment]
> If the build doesnt fetch any firmware then the archive wont be used but it will be available (which it isnt prior to this commit).

The repo list is actually emptied out on VyOS bootup as this is an image based distribution over a package based

> This is handy specially for custom builds were you wont have to troubleshoot why a specific package who exists in Debian suddently doesnt install in the chroot build directory.

So this is a theoretical issue but I get the point. We should not make any life harder then it is.

**Review by c-po — APPROVED** [review]

**Comment by Apachez-** [comment]
> > If the build doesnt fetch any firmware then the archive wont be used but it will be available (which it isnt prior to this commit).
> 
> The repo list is actually emptied out on VyOS bootup as this is an image based distribution over a package based
> 
> > This is handy specially for custom builds were you wont have to troubleshoot why a specific package who exists in Debian suddently doesnt install in the chroot build directory.
> 
> So this is a theoretical issue but I get the point. We should not make any life harder then it is.

This affects building of VyOS.

When VyOS is running there are no sources.list configured.

**Pull request merged**
