### PR TITLE
ddclient: T5797: switch to Debian SALSA repository

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary

Commit 368b89ef05 ("ddclient: T5797: Upgrade to ddclient 3.11.2") bumped the ddclient version by using the build system from Debian SALSA repo and the upstream ddclient source code.

Debian now provides the same version from the SALSA repos.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5797

## Component(s) name

ddclient

## How to test

Smoketests

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
@MergifyIo backport circinus sagitta

**Comment by indrajitr** [comment]
Thanks @c-po! We can now remove [build.sh](https://github.com/vyos/vyos-build/blob/current/packages/ddclient/build.sh) as well.

**Review by sever-sever — APPROVED** [review]

**Review by jestabro — APPROVED** [review]

**Comment by marekm72** [comment]
https://vyos.dev/T5797 seems completely unrelated to ddclient - what is the correct task?

**Comment by indrajitr** [comment]
That should have been https://vyos.dev/T5792. I had a typo in the previous PR, my apologies.

**Pull request merged**
