### PR TITLE
T6231: Mellanox OFED

### PR DESCRIPTION
**Pull request by sempervictus**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

[T6231](https://vyos.dev/T6231)
## Component(s) name
Mellanox (Nvidia) OFED kernel and userspace

## Proposed changes

OFED stack: drivers, userspace utilities, libraries, and DPDK/VPP interfaces.

## How to test
1. run included script in build stack
2. deploy the debs with the kernel built from the referenced sources
3. boot on host with ConnectX card
4. verify which module is loaded and features available

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
There are unrelated to this task commits
Why do you add them?

**Comment by sempervictus** [comment]
Git fun it seems :-/ - I just checked out `-b` and cherry picked my commit on it then added the Jenkinsfile one... Not sure how GH turned that into this. Rebased

**Comment by zdc** [comment]
Are there any examples of specific issues with upstream drivers fixed in OFED, or important for VyOS case benefits available in OFED and not available upstream?

**Comment by sempervictus** [comment]
,

> Are there any examples of specific issues with upstream drivers fixed in OFED, or important for VyOS case benefits available in OFED and not available upstream?

Addresses a few things:
Ever try to get line rate comms above connectx4, hw offload for complex functions, or vendor support when using upstream? First thing nv says in the support process is to use their drivers... We were struggling to route/nat more than 40gbit on upstream, were able to get nearly 200 going through inside lacp bond through outside lacp bond on OFED on cx6 and 7+ are a whole other ballgame. Its not as bad as difference between nouveau and actual GPU drivers from nv but well worth the change despite making kCFI that much more of a challenge (they hardcode GCC, for now) since this is a NOS.

**Comment by zdc** [comment]
> We were struggling to route/nat more than 40gbit on upstream, were able to get nearly 200 going through inside lacp bond through outside lacp bond on OFED on cx6 and 7+

Can you confirm that in the described case a driver replacement was the only difference? The same device, same connections, same performance tester, same configuration, just another driver?

I have no objections against adding OFED drivers, but we need to understand the real profit from this.

**Comment by sempervictus** [comment]
Yes, same device rebooted to an image containing ofed

**Review by c-po — CHANGES_REQUESTED** [review]
Can both drivers co-exist or does the stock driver needs to be removed from the Kernel?

How does the system determine which to load? Or dies it go the usual way in detecting "there is a newer driver in `/lib/modules/6.6.35/updates/dkms`?

Issue: `-amd64-vyos` is missing from the installation path of the new modules, see `KERNEL_SUFFIX` environment variable also present in `packages/linux-kernel/kernel-vers`

**Comment by sempervictus** [comment]
> Can both drivers co-exist or does the stock driver needs to be removed from the Kernel?
>
both can coexist and you can `insmod` by path if you want to use the upstream ones.
> How does the system determine which to load? Or dies it go the usual way in detecting "there is a newer driver in `/lib/modules/6.6.35/updates/dkms`?
>
the `updates` paths are how DKMS and such do this as well - upstream Linux semantic

> Issue: `-amd64-vyos` is missing from the installation path of the new modules, see `KERNEL_SUFFIX` environment variable also present in `packages/linux-kernel/kernel-vers`
>
i havent found this to be an issue on any distribution over the ages and all of our kernels on all of our own OS forks and upstream ones utilize suffixes while DKMS and many out-of-tree drivers don't. Remedy would require changing the vendors source which is doable, but adds hassle/maintenance burden as their code changes rev to rev.

On that note, the suffix thing is rather constraining as implemented - we use different suffixes to denote specific kernel build types and tag our images with them (LLVM+hardened, GCC+hardened, GCC+grsec/pax, etc) because we cannot build an image with multiple kernels to let the user choose what to boot. IIRC this was was one of the big blockers to #132 - we couldn't get people to test anything to figure out what and how we should implement. I do have a much better "piecemeal it in" strategy for that code moving forward (actually been testing with this PR in our builders - `linux-hardened` and the `xtables` stuff drops in nicely now though i think we should just pull from `linux-hardened` for the source tree and adjust the version tag) but we still have to build dedicated images with those kernels as opposed to making a boot option (in part due to how the build scripts generate `initramfs`)

**Comment by c-po** [comment]
Moved drivers to appropriate directory and added some other minor changes to this pr

`-rw-r--r-- root/root   5218104 2012-12-31 13:38 ./lib/modules/6.6.41-amd64-vyos/updates/dkms/mlx5_core.ko`

**Review by c-po — APPROVED** [review]

**Review by zdc — APPROVED** [review]

**Pull request merged**
