### PR TITLE
vyos-build: T2854: Build python3-trio Debian package

### PR DESCRIPTION
**Pull request by bob1de**
trio is not available in buster because it's too young, it will probably
be in bullseye. The package is required by vyos.client_server.

This is the successor of #122.

### CODE REVIEW

**Comment by bob1de** [comment]
I actually don't know how to test if the Jenkinsfile works as intended. Do I have to register it somewhere to be picked up or will it be found automatically?

**Comment by bob1de** [comment]
Ah, I see, a new Jenkins pipeline would need to be created I guess... Can't do this myself, right?

**Comment by andamasov** [comment]
@sever-sever @dmbaturin @c-po is this still an actual problem? or we should close it?

**Comment by c-po** [comment]
@jestabro would know best

**Comment by bob1de** [comment]
From my side, this is not required anymore since the actual work depending on it has been abandoned. So I'll close it right away. Thanks for the reminder.

**Pull request closed without merging**
