### PR TITLE
packer: T6390: Compensate for packer packaging update

### PR DESCRIPTION
**Pull request by cjac**
packer: T6390: Compensate for packer packaging update

new packer zip file comes with license as well as the packer binary.
compensate for this while not breaking old code

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
Hey, long time no see!

We don't use Packer ourselves, but if it fixes the process for those who do, I have nothing against the fix.

**Comment by cjac** [comment]
Hey there!

Then I'll clean it up a bit today.

**Comment by sever-sever** [comment]
@cjac Could you create a task on https://vyos.dev/ and add the task number to the commit message and PR header?
More details 
https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md
https://blog.vyos.io/pull-request-creation-guidelines

**Comment by cjac** [comment]
I'd be happy to.  Please give me until about noon.  The kiddo is sick and needs some attention first.

**Comment by cjac** [comment]
https://vyos.dev/T6390

**Comment by cjac** [comment]
My docker build shows that this updated RUN command succeeds

**Comment by cjac** [comment]
Full docker build succeeds.  I approve of this change.

```
 => [66/67] RUN echo -e "set mouse=\nset ttymouse=" > /etc/vim/vimrc.loca  0.5s
 => [67/67] COPY entrypoint.sh /usr/local/bin/entrypoint.sh                0.1s
 => exporting to image                                                     7.8s
 => => exporting layers                                                    7.7s
 => => writing image sha256:a908bd97d1339c0984d448121a2bb15ee93edef573709  0.0s
 => => naming to docker.io/vyos/vyos-build:equuleus                        0.0s
```

**Comment by sever-sever** [comment]
every change must be associated with a task number
(prefixed with **T**) and a component. If there is no bug report/feature
request for the changes you are going to make, you have to create a development portal
task first. Once there is an entry in the development portal, you should reference its id
in your commit message, as shown below:

* `ddclient: T1030: auto create runtime directories`

**Comment by cjac** [comment]
@sever-sever - PR message updated.  Please review.

**Comment by sever-sever** [comment]
> @sever-sever - PR message updated. Please review.

The commit message is not fixed
commit-message

**Comment by cjac** [comment]
okay.  commit message amended in addition to the PR message.

**Review by sever-sever — APPROVED** [review]

**Pull request merged**
