### PR TITLE
ddclient: T5792: Use Debian build from Trixie

### PR DESCRIPTION
**Pull request by indrajitr**
As part of "T5792: Upgrade to ddclient 3.11.2" in commit 368b89ef056, ddclient was built using build system from Debian Salsa and source code from upstream GitHub.

This was subsequently modified in commit 7f7030d9281 to use both build system and source code from Debian Salsa.

Now that Debian has finally released ddclient 3.11.2 for Trixie, we can use the Trixie build directly instead of the custom build.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T5792

## Component(s) name

service dns dynamic

## How to test

smoketest

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta circinus

**Review by dmbaturin — COMMENTED** [review]
I'd be uneasy about that, to be fair. Using packages from newer Debian versions is all fun and dandy — until they update glibc or some other dependency there that we can't update. That happened with Podman recently.

Is there a strong guarantee that it will not happen with ddclient?

**Comment by indrajitr** [comment]
@dmbaturin, yes I have been debating about that as well.
And here is where my mind has been:
- ddclient is just a perl script with some [basic dependencies](https://packages.debian.org/sid/ddclient#pdeps)
- unless the package maintainers want to overcomplicate things, chances are dependency versions won't change much

That said, it is still theoretically possible (although less likely) that the dependency changes midway before Trixie goes GA.

I'll be open to making the changes in the PR to do a custom build instead if that is what the overall recommendation is.

**Comment by c-po** [comment]
> I'll be open to making the changes in the PR to do a custom build instead if that is what the overall recommendation is.

Please do so - we have this way for other packages, too

**Comment by indrajitr** [comment]
> > I'll be open to making the changes in the PR to do a custom build instead if that is what the overall recommendation is.
> 
> Please do so - we have this way for other packages, too

Update pushed

**Comment by c-po** [comment]
@MergifyIo backport sagitta circinus

**Review by sever-sever — APPROVED** [review]

**Comment by sever-sever** [comment]
Smoketest fails

DEBUG - test_08_dyndns_vrf (__main__.TestServiceDDNS.test_08_dyndns_vrf) ... FAIL
DEBUG - test_08_dyndns_vrf (__main__.TestServiceDDNS.test_08_dyndns_vrf) ... FAIL
DEBUG - FAIL: test_08_dyndns_vrf (__main__.TestServiceDDNS.test_08_dyndns_vrf)
DEBUG - FAIL: test_08_dyndns_vrf (__main__.TestServiceDDNS.test_08_dyndns_vrf)
DEBUG - FAILED (failures=2)
ERROR - Smoketest failed :/
ERROR - Unknown error occured while VyOS!
ERROR - Hmm... system got an exception while processing.
ERROR - The ISO image is not considered usable!
DEBUG - AssertionError: 'ddclient' not found in ''
DEBUG - 
DEBUG - ======================================================================
DEBUG - FAIL: test_08_dyndns_vrf (__main__.TestServiceDDNS.test_08_dyndns_vrf)
DEBUG - ----------------------------------------------------------------------
DEBUG - Traceback (most recent call last):
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py", line 49, in tearDown
DEBUG -     self.assertTrue(process_running(DDCLIENT_PID))
DEBUG - AssertionError: False is not true
DEBUG - 
DEBUG - ----------------------------------------------------------------------
DEBUG - Ran 8 tests in 63.467s
DEBUG - 
DEBUG - FAILED (failures=2)
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_service_dns_forwarding.py
DEBUG - test_basic_forwarding (__main__.TestServicePowerDNS.test_basic_forwarding) ... ok

**Comment by indrajitr** [comment]
Looks like the test case for vrf is failing. Did something change recently on vrf side?

**Pull request merged**
