### PR TITLE
T3664: Eliminate obsolete build flavours

### PR DESCRIPTION
**Pull request by UnicronNL**

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
Looks good to me. Let's remove the old legacy to make room for a new implementation.

**Comment by c-po** [comment]
`make qemu` is actually used by the Pipeline script (optionally) https://github.com/vyos/vyos-build/blob/current/Jenkinsfile#L139

If it goes from the Makefile, please also clean out the Qemu build option form Jenkins. Then it can be merged for sure.

**Comment by dmbaturin** [comment]
Let's disable the pipeline until a new implementation is in place.

The plan is to redo the implementation so that it doesn't need packer et al.

**Comment by c-po** [comment]
You mean disable the Pipeline at al? Then we would have no more rollings.

As Qemu as currently only used if someone actively selects it during a build I'd rather simply drop the calling code and leave the pipeline in place

**Comment by dmbaturin** [comment]
Wait, I misunderstood you. Can we disable just the Qemu build for now?

**Comment by c-po** [comment]
Yep, it is an optional parameter.

**Comment by c-po** [comment]
I have dropped the optional parameter in 0ba721e3f1c60be9fbb03b3c6e9867d795f5cfca - it is save to merge this now.

**Pull request merged**
