### PR TITLE
T5123: Use 'patch' instead of 'git am' to make it more robust

### PR DESCRIPTION
**Pull request by rgwan**
Refer to pull request #342 and #328, `git am` seems still not working.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5123

## Component(s) name

ospfd

## How to test

Use command `show ip ospf route detail` to show detailed information.
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I see no need for this as it works as expected. `git am` also support creating a proper git commit - wheras `patch` would result in a dirty workspace.

**Comment by rgwan** [comment]
> I see no need for this as it works as expected. `git am` also support creating a proper git commit - wheras `patch` would result in a dirty workspace.

Okay, which frr commit is used by vyos now? Can I see some build logs?

**Comment by c-po** [comment]
We use `stable/8.5` branch from FRR repo: https://github.com/vyos/vyos-build/blob/current/packages/frr/Jenkinsfile#L29

And the build logs (which are temporary private due to a Jenkins bug) say:

```
[2023-04-28T17:03:06.859Z] + cd ..
[2023-04-28T17:03:06.859Z] + ./build-frr.sh
[2023-04-28T17:03:06.859Z] I: Apply FRRouting patches not in main repository:
[2023-04-28T17:03:06.859Z] Applying: ospfd: Support show advertise router in 'show ip ospf route' command
[2023-04-28T17:03:06.859Z] Applying: ospfd: Fix wrong advertise router calculation in transit network
[2023-04-28T17:03:06.859Z] Applying: ospfd: Support show intra-area network type in 'show ip ospf route' command
[2023-04-28T17:03:06.859Z] I: Build Debian FRR Package
[2023-04-28T17:03:07.306Z] dch warning: neither DEBEMAIL nor EMAIL environment variable is set
[2023-04-28T17:03:07.306Z] dch warning: building email address from username and FQDN
[2023-04-28T17:03:07.306Z] dch warning: Previous package version was Debian native whilst new version is not
[2023-04-28T17:03:07.306Z] dch: Did you see those 2 warnings?  Press RETURN to continue...
[2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source package frr
[2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source version 8.5.1-6-g447423687
[2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source distribution UNRELEASED
[2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source changed by Jafar Al-Gharaibeh <vyos_bld@56cda14e6dee>
[2023-04-28T17:03:07.306Z]  dpkg-source --before-build .
[2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: host architecture amd64
[2023-04-28T17:03:07.754Z]  fakeroot debian/rules clean
[2023-04-28T17:03:08.201Z] dh clean -Bbuild --with=sphinxdoc
[2023-04-28T17:03:08.201Z]    dh_testdir -O-Bbuild
[2023-04-28T17:03:08.201Z]    debian/rules override_dh_auto_clean
[2023-04-28T17:03:08.201Z] make[1]: Entering directory '/home/admin/workspace/vyos-build-frr_current/build-amd64/packages/frr/frr'
[2023-04-28T17:03:08.201Z] if test -f Makefile; then make redistclean; fi
[2023-04-28T17:03:08.201Z] rm -f debian/frr.init
[2023-04-28T17:03:08.201Z] rm -f debian/frr.service
```

**Comment by rgwan** [comment]
> We use `stable/8.5` branch from FRR repo: https://github.com/vyos/vyos-build/blob/current/packages/frr/Jenkinsfile#L29
> 
> And the build logs (which are temporary private due to a Jenkins bug) say:
> 
> ```
> [2023-04-28T17:03:06.859Z] + cd ..
> [2023-04-28T17:03:06.859Z] + ./build-frr.sh
> [2023-04-28T17:03:06.859Z] I: Apply FRRouting patches not in main repository:
> [2023-04-28T17:03:06.859Z] Applying: ospfd: Support show advertise router in 'show ip ospf route' command
> [2023-04-28T17:03:06.859Z] Applying: ospfd: Fix wrong advertise router calculation in transit network
> [2023-04-28T17:03:06.859Z] Applying: ospfd: Support show intra-area network type in 'show ip ospf route' command
> [2023-04-28T17:03:06.859Z] I: Build Debian FRR Package
> [2023-04-28T17:03:07.306Z] dch warning: neither DEBEMAIL nor EMAIL environment variable is set
> [2023-04-28T17:03:07.306Z] dch warning: building email address from username and FQDN
> [2023-04-28T17:03:07.306Z] dch warning: Previous package version was Debian native whilst new version is not
> [2023-04-28T17:03:07.306Z] dch: Did you see those 2 warnings?  Press RETURN to continue...
> [2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source package frr
> [2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source version 8.5.1-6-g447423687
> [2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source distribution UNRELEASED
> [2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: source changed by Jafar Al-Gharaibeh <vyos_bld@56cda14e6dee>
> [2023-04-28T17:03:07.306Z]  dpkg-source --before-build .
> [2023-04-28T17:03:07.306Z] dpkg-buildpackage: info: host architecture amd64
> [2023-04-28T17:03:07.754Z]  fakeroot debian/rules clean
> [2023-04-28T17:03:08.201Z] dh clean -Bbuild --with=sphinxdoc
> [2023-04-28T17:03:08.201Z]    dh_testdir -O-Bbuild
> [2023-04-28T17:03:08.201Z]    debian/rules override_dh_auto_clean
> [2023-04-28T17:03:08.201Z] make[1]: Entering directory '/home/admin/workspace/vyos-build-frr_current/build-amd64/packages/frr/frr'
> [2023-04-28T17:03:08.201Z] if test -f Makefile; then make redistclean; fi
> [2023-04-28T17:03:08.201Z] rm -f debian/frr.init
> [2023-04-28T17:03:08.201Z] rm -f debian/frr.service
> ```

Okay, it works correctly! Thank you!

**Pull request closed without merging**
