### PR TITLE
T3489 - Re-Enable NUMA (and kexec)

### PR DESCRIPTION
**Pull request by xrobau**
## Change Summary
Enable NUMA and kexec on current VyOS kernels

## Types of changes

 
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [X] Other (please describe):

All throughout the history of vyos-build, NUMA has been disabled.
It WAS enabled back in Vyatta days, so something somewhere has
accidentally turned it off - and it's ALSO mentioned explicitly
in various pieces of documentation, so it's MEANT to be on!

This also enables kexec for faster reboots.

## Component(s) name

kernel

## How to test

Build Kernel. Check to make sure that `numa_` variables are present in 

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Hi @xrobau, thanks for the PR.

Please note as NUMA and keyec are two things, so they should be submitted as two individual commits. Also your commit headline does not come with the required Task id - this is only set on the PR topic, but must be present on the commit itself.

**Review by c-po — CHANGES_REQUESTED** [review]
Plese split kexec and NUMA in two commits.

**Comment by xrobau** [comment]
Split into two, and fixed the INOTIFY config option I missed, too.

**Comment by xrobau** [comment]
Updated to fix conflicts.

**Comment by c-po** [comment]
Added via

* 91a108e - Kernel: T3489: enable kexec support
* d5df496 - Kernel: T3489: re-enable NUMA in kernel build

**Pull request closed without merging**
