### PR TITLE
T6293: add Mediatek MT7921 to defconfig

### PR DESCRIPTION
**Pull request by SaulGoodman1337**
set 
CONFIG_MT7921E=m
CONFIG_MT7921S=m
CONFIG_MT7921U=m

## Change Summary
i have activated the three modules because these drivers are missing in the current vyos kernel.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Component(s) name
wifi

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
@SaulGoodman1337 Could you read CONTRIBUTING document "prepare commit"? 
```
To make this approach work, every change must be associated with a task number (prefixed with T) and a component.
If there is no bug report/feature request for the changes you are going to make, you have to create a development portal task first.
Once there is an entry in the development portal, you should reference its id in your commit message, as shown below:

    ddclient: T1030: auto create runtime directories
    Jenkins: add current Git commit ID to build description

```
It requires the task number in the head of PR and in the commit message.
Thanks

**Comment by SaulGoodman1337** [comment]
> @SaulGoodman1337 Could you read CONTRIBUTING document "prepare commit"?
> 
> ```
> To make this approach work, every change must be associated with a task number (prefixed with T) and a component.
> If there is no bug report/feature request for the changes you are going to make, you have to create a development portal task first.
> Once there is an entry in the development portal, you should reference its id in your commit message, as shown below:
> 
>     ddclient: T1030: auto create runtime directories
>     Jenkins: add current Git commit ID to build description
> ```
> 
> It requires the task number in the head of PR and in the commit message. Thanks

dont know how to change the commit message

**Comment by c-po** [comment]
`git commit --amend`

**Comment by c-po** [comment]
No need to create a new PR, you can always `git push --force` to your old branch after ammending or rebasing.

Superseeded by https://github.com/vyos/vyos-build/pull/584.

**Pull request closed without merging**
